# Generated by Django 5.0.7 on 2024-07-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='picture',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
